### ISSUE TITLE
When NotchCostUI is enabled, sent charms should not say charm count in RecentItemsDisplay

### ISSUE THREAD

**Issue by Ijwu** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#10]
When using charm notch rando, the NotchCostUI ItemChanger module is auto-enabled. Currently, if you send a charm to another player it will appear in your RecentItemsDisplay and tell you the notch cost for that charm for yourself. This is a spoiler, and should probably be changed.

**Comment by BadMagic100** [comment]
I have a hunch that the solution to #133 will help here - the recommended solution from Shadu is to just copy the container and UIDef onto a dummy item so NotchCostUI should no longer recognize the remote items as real charms

**Comment by BadMagic100** [comment]
This is currently fixed in development
