### ISSUE TITLE
Prevent access to THK when goal conditions are not met

### ISSUE THREAD

**Issue by dewiniaid** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#106]
We can prevent the THK fight from starting by activating the gate in the room on scene change if goal conditions are not met.  While this doesn't prevent all possible 'invalid' endings on its own (namely, Sealed Siblings is doable when the goal is Radiance), it eliminates some of them.

Some research:

Final boss scene is `Room_Final_Boss_Core`
The gate GameObject is simply named `Gate`.
It has three children: `Final_Boss_Gate0004`, `Collider` and `CameraLockArea B`

We shouldn't activate the cameralock because it causes the camera to lock to the THK fight.  But activating the other two makes the gate visible and prevents the player from walking through it.

The collider is abnormally large and the gate faces away from the player when approached from this direction.  We can alter the gate's `Transform` as follows to make it (mostly) match up with the collider:

Set the X value to negative its current value to flip the sprite to face the player
set the X value of Localposition to about -8.15

**Comment by BadMagic100** [comment]
Between focus and benchwarp, players are able exit the fight if they cannot complete their goal. Closing as wontfix
