### ISSUE TITLE
Basin Fountain cost is doubled

### ISSUE THREAD

**Issue by BadMagic100** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#123]
**Describe the bug**
When NPC dialog is not disabled in ItemChanger, the basin fountain double-charges.

**To Reproduce**
1. Enable NPC item dialog in ItemChanger settings (this is on by default)
2. Pay 3000 geo to the fountain
3. The given shiny will also have an associated cost

**Expected behavior**
The fountain should only charge once.

**Screenshots**

**Additional context**
This is likely due to the implicit cost at the fountain not being respected - the fountain interaction takes 3k geo, then grants a shiny with an additional IC cost assigned.

**Comment by thislooksfun** [comment]
I can confirm this is happening.

**Comment by BadMagic100** [comment]
Did a bit of research on this. The fix would be in [this method](https://github.com/Ijwu/Archipelago.HollowKnight/blob/main/Archipelago.HollowKnight/ArchipelagoRandomizer.cs#L311) , instead of immediately creating the cost,  to scan the location for implicit costs (specifically with inherent=true because AP explicitly handles non-inherent implicit costs like cornifer), check if any of those costs include the cost about to be added, and only add the cost if it is not included in the inherent costs.

Seems like a fairly easy fix but I am too entrenched in other projects to get AP building and test locally

**Comment by dewiniaid** [comment]
This is fixed in development, but your fix might be better -- I'll look in
to it

**Comment by BadMagic100** [comment]
I'd have to see how it's fixed in dev but yes I assume that my proposed fix is more future-proof against other locations where this may occur, if the dev fix isn't already doing this

**Comment by BadMagic100** [comment]
Resolved by bbe9776cf691d924e7ff4bd51aba28f2ceb19c2c
