### ISSUE TITLE
Invalid saved connection info renders saves unplayable

### ISSUE THREAD

**Issue by alwaysintreble** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#124]
Connection info is saved to the save file. While on webhost the port gets stored in the multisave it does not reserve the port when the room gets shut down so a new room can be opened, taking the port. This causes the first room to be opened on a new port when it gets opened back up rendering the save unable to connect. Need a way to modify the port if the save is unable to connect to the server.

**Comment by dewiniaid** [comment]
As a workaround to this issue until a better fix is available, you can edit
your `userX.modded.json` (where X is the save slot) file to update
connection details.

It's located alongside your save data -- I'm on mobile so this path might
be slightly wrong but I believe it's under `%Appdata\..\LocalLow\Team
Cherry\Hollow Knight`

**Comment by Ijwu** [comment]
Twisting this into a feature request for the ability to alter save slot connection details.

**Comment by BadMagic100** [comment]
Ijwu did some work on this, will work on it towards the next release https://github.com/ArchipelagoMW-HollowKnight/Archipelago.HollowKnight/tree/feature/resume_menu
