### ISSUE TITLE
Grub count showing on pick up when collecting vanilla grub locations.

### ISSUE THREAD

**Issue by KonoTyran** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#172]
**Describe the bug**
vanilla grub locations append the grub count onto the end of the item that was there

**Additional context**
repoted in discord by TerraFail, God of Failure, https://discord.com/channels/731205301247803413/959203442570715176/1135992811309781072

needs Investigation.

**Comment by BadMagic100** [comment]
The issue is purely on the grubnames side
