### ISSUE TITLE
Hint tracker should update hint list when obtained an item

### ISSUE THREAD

**Issue by BadMagic100** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#188]
**Describe the bug**
When collecting a hinted item from your world, the hint list doesn't update.

**Expected behavior**
The hint list should update 

**Additional context**
The hint tracker module could subscribe to aftergiveglobal . When receiving a hinted item:
1. Update the hint in the hint list to "found" (if needed/possible)
2. Fire the hint update event

**Comment by BadMagic100** [comment]
cc @KonoTyran does this seem like a sane thing to do/a sane way to do it?

**Comment by KonoTyran** [comment]
Yea this is probably the best way to work around the issue of AP not correctly updating us when the status of hints change. Should be simple enough to check if`ArchipelagoItemTag.Location` is in the hint list and mark it as found.
