### ISSUE TITLE
Fix Grimmkin Flame Rando

### ISSUE THREAD

**Issue by Ijwu** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#2]

**Comment by Berserker66** [comment]
Doing flame checks with grimmkin awards/sends the item. Have not yet checked how the "quest" for king grimm works out.

**Comment by Hedgehog0** [comment]
For now Grimmchild doesn't require Flames to evolve, but they can still be randomized and found in checks.

**Comment by BadMagic100** [comment]
Can confirm this is still occurring, we need to place grimmchild1 instead of grimmchild2 when flames are randomized

**Comment by BadMagic100** [comment]
resolved on the AP side
