### ISSUE TITLE
Abyss Shriek marked as reachable without Howling Wraiths

### ISSUE THREAD

**Issue by rabahber** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#209]
During a multiworld randomiser with a friend on OoT we got stuck. Game expected me to get their bomb bag from abyss shriek. Couldn't get the check, since howling wraiths was not obtained yet.

attached is the seed log
[spoiler log](https://github.com/ArchipelagoMW-HollowKnight/Archipelago.HollowKnight/files/13694180/spoiler.log)

**Comment by BadMagic100** [comment]
If you check your playthrough, you will find that there is a wraiths (Abyss_Shriek) in the sphere 57, just before the bomb bag, at Arcane_Egg-Birthplace. Your King's Brand is at Fury of the Fallen. Void_Heart is in Sphere 1 at Chrissi's LH Deku Scrub Grotto Right, and King_Fragment is in sphere 19 at Chrissi's Bottom of the Well Front Left Fake Wall Chest which will give you a Kingsoul for birthplace access once you get to Basin. Your storerooms stag is at your hornet, giving you basin access via waterways into the broken elevator.

Please thoroughly validate the playthrough in your spoiler log to validate exactly what expected requirement is missing from logic in the future and that the location is actually unreachable in the future before submitting logic bugs in the future. If needed, don't hesitate to use the Archipelago Discord server to get help with this; the community can help verify that there actually is a bug, or if you just don't know the logical path as was the case in this instance
