### ISSUE TITLE
[Hollow Knight] The map mod wrongly showing JunkPitChests as not randomized

### ISSUE THREAD

**Issue by FlorianDeSmedt** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#214]
Most options for randomizeX were put on random. RandomizeJunkPitChests rolled randomized, but showed as not randomized on the map mod.

RandomizeDreamers:               No
RandomizeSkills:                 Yes
RandomizeFocus:                  No
RandomizeSwim:                   Yes
RandomizeCharms:                 No
RandomizeKeys:                   No
RandomizeMaskShards:             Yes
RandomizeVesselFragments:        Yes
RandomizeCharmNotches:           Yes
RandomizePaleOre:                No
RandomizeGeoChests:              No
RandomizeJunkPitChests:          Yes
RandomizeRancidEggs:             No
RandomizeRelics:                 No
RandomizeWhisperingRoots:        No
RandomizeBossEssence:            No
RandomizeGrubs:                  No
RandomizeMimics:                 Yes
RandomizeMaps:                   No
RandomizeStags:                  Yes
RandomizeLifebloodCocoons:       Yes
RandomizeGrimmkinFlames:         No
RandomizeJournalEntries:         No
RandomizeNail:                   Yes
RandomizeGeoRocks:               No
RandomizeBossGeo:                No
RandomizeSoulTotems:             No
RandomizeLoreTablets:            No
Randomize Elevator Pass:         No

These are the settings that were rolled

![image](https://github.com/ArchipelagoMW-HollowKnight/Archipelago.HollowKnight/assets/104439321/f0b7629f-741b-4cb9-ab4e-632805ab16bc)

https://archipelago.gg/dl_spoiler/5Zi21F0TRdS4l5ezZJExwA

Possibly the JunkPitChests are wrongly listed in the GeoChest category in the map mod instead of having their own category?
There were 2 teams on this seed (a competetive async) and both teams encountered this issue

**Comment by BadMagic100** [comment]
This is a map mod bug, please open on the map mod repo https://github.com/ArchipelagoMW-HollowKnight/Archipelago.APMapMod
