### ISSUE TITLE
Steam Cloudsync brakes AP connection on Multi-Platform sessions.

### ISSUE THREAD

**Issue by Sk4lli** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#217]
**Describe the bug**
Wont connect to Archipelago on Steam Synced Save for another Platform.

**To Reproduce**
 0. Install Steam + Hollow Knight
 1. Install Archipelago following the Guide
     https://archipelago.gg/tutorial/Hollow%20Knight/setup/en
      on the First Plattform , My Case Win11
2. Launch Game with the Modlauncher
3. Start new AP Game.
4. Enter your AP server details and start.
5. (optional) Play the Game for a bit
6. Exit the game and let Steam sync the Save into the cloud.
7. Repeat Step 0 & 1 for another Platform , in my case MacOs 13 (intel) (Game and ModLauncher are available) 
8. Repeat Step 2
9. Resume Saved Game

**Expected behavior**
Re-Enter Server Details and resume the AP Run.

**Screenshots**
no screenshot because i cant show something which isn't even there.

**Additional context**
Under normal Circumstances i would expect that i have to re-enter the AP server details or review them if they are correct.
In this Case the synced Savegame is loaded like any other Savegame without AP connected, even the site with the Server Details isn't showing up.

i haven't found any log, if you can tell me the location of the log files i will provide them.

**Comment by BadMagic100** [comment]
This is not an Archipelago issue, closing.

The modding api deliberately stores modded save data separately from vanilla save data in order to prevent corrupting the file when unmodding the game. Modded save data is not synced by steam cloud. As far as I know there is not any plan to change this either.
