### ISSUE TITLE
Mantis claw inaccesable 

### ISSUE THREAD

**Issue by Justin-Gold** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#225]
**Describe the bug**
Mantis Claw was randomized to an inaccessible position as far as I can tell. Checking the spoiler log the mantis claw was randomized to be in the Mask_Shard-Queen's_Station location, but as far as I can tell there is no possible way to get to that check without the mantis claw. Additionally all the skips are disabled. Here is a link to the spoiler log https://archipelago.gg/dl_spoiler/qjrfdL9vQbyudv_M_yb9Wg. 

**To Reproduce**
1. get very unlucky 
2. try to get mantis claw
3. fail
4. cry

**Comment by BadMagic100** [comment]
You have access to wings in the sphere just prior (at seer). QS mask shard is accessible with wings by doing 2 full-height wings jumps, no bug here.
