### ISSUE TITLE
Hall of Gods checks

### ISSUE THREAD

**Issue by Avasam** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#233]
I would like to see Hall of Gods checks added to the Archipelago Randomizer.
For reference, here's a non-AP rando addon that does it: https://github.com/nerthul11/GodhomeRandomizer#hall-of-gods and the associated options: https://github.com/nerthul11/GodhomeRandomizer#hall-of-gods-1

I think the way it handles it is perfectly fine as-is. (especially the options to not have radiant and ascended be checks)

Some way to preview the boss checks would be nice though, to avoid grinding a hard boss with incomplete inventory for a useless check.

**Comment by BadMagic100** [comment]
This will fall under #147

**Comment by Avasam** [comment]
Oh I missed that issue. Thanks!
Good luck on trying to make this work with AP
