### ISSUE TITLE
Connection Timing Out

### ISSUE THREAD

**Issue by Honey671** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#235]
For some reason when I try and press start on a new save it says "CONNECTION TIMED OUT."

I don't know if it is just for me because I cant find any guides on what to do if its doing this

![image_2024-12-22_175955131](https://github.com/user-attachments/assets/7cb09519-741f-4964-b2ae-db1873a26760)

**Comment by BadMagic100** [comment]
This would typically indicate a network issue and would not be an issue with the mod. I can suggest to double check your network connection and all your connection details (port, slot, password) and if that doesn't work you can ask the tech support channels in the Archipelago discord server
