### ISSUE TITLE
Version 0.7.0 does not send or receive items in multiworld

### ISSUE THREAD

**Issue by ardputten** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#237]
**Describe the bug**
I and another player also on Hollow Knight were unable to send/receive items from the multiworld with the latest version (0.7.0) of the mod. We were also unable to open the menu (escape). One of us had randomized nail and was in one attempt (new randomization/server restart) able to slash in all directions, and in another attempt in no directions at all. Previous version from Github releases works fine.

**To Reproduce**
1. Install the Archipelago randomizer mod from Lumafly
2. Install and set up an Archipelago server (latest version, 0.5.1)
3. Connect to the Archipelago server
4. Attempt to pick up items (will show in game correctly ("Other player's 15 geo") but the server/other player does not receive them)

**Additional context**
The multiworld was for one player on Dark Souls III and two players on Hollow Knight. Archipelago map mod was also installed, although there might have been an attempt without it installed that still failed.

**Comment by BadMagic100** [comment]
Thanks for the report, i did identify the bug prior to this but having this to track it is fine. I will have a fix out shortly
