### ISSUE TITLE
Non-randomized placements should not grant hint points

### ISSUE THREAD

**Issue by Ijwu** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#56]

**Comment by Alchav** [comment]
I take it from the "server-side" tag that making the non-randomized items handled locally is not in the cards, and that they must come from the server?

**Comment by Alchav** [comment]
I'm working on a server-side solution

**Comment by BadMagic100** [comment]
New proposal for this is we will make a toggle (default off) to place vanilla items for coop purposes. I do see the value in the feature as implemented but I don't believe that it's correct as the default, as evidenced by the number of people that have complained about it

**Comment by BadMagic100** [comment]
Addressed on the AP side in 0.4.5. Necessary changes to shops done in 723293593712208efbbcc41b4a2952b9ea9c28b0
