### ISSUE TITLE
/send errors

### ISSUE THREAD

**Issue by KonoTyran** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#79]
When using `/send (name) geo rock - default` in the server console it fails to properly receive the item after the first occurrence.
Instead receiving "swim" and "focus"

[ModLog.txt](https://github.com/Ijwu/Archipelago.HollowKnight/files/8904511/ModLog.txt)

**Comment by BadMagic100** [comment]
Verified this is no longer occurring
